name: l10n_mapper_annotation
description: A dart package to generate localization-mapper to support parsing dynamic translation keys (as flutter-localizations package does not yet support this).
version: 1.2.0
homepage: https://github.com/kwado-tech/l10n_mapper/tree/main/l10n_mapper_annotation
repository: https://github.com/kwado-tech/l10n_mapper/tree/main/l10n_mapper_annotation

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
